version: '3.0'
services:
  app:
    build: .
    command: ['sh', './test.sh']
    volumes:
      - .:/workdir
      - data:/data
  scheduler:
    build: .
    command: ['dask-scheduler', '--host', '0.0.0.0']
    volumes:
      - .:/workdir
      - data:/data
  worker:
    build: .
    command: ['dask-worker', '--nthreads', '1', 'scheduler:8786']
    volumes:
      - .:/workdir
      - data:/data
    environment:
      - PYTHONPATH=/workdir
volumes:
  data:
    driver: local
