version: '3.0'
services:
  app:
    build: .
    command: ['sh', './test.sh']
    volumes:
      - .:/workdir
      - data:/data
    environment:
    - MINIO_ACCESS_KEY
    - MINIO_SECRET_KEY
    depends_on:
    - minio
  scheduler:
    build: .
    command: ['dask-scheduler', '--host', '0.0.0.0']
    volumes:
      - .:/workdir
      - data:/data
  worker:
    build: .
    command: ['dask-worker', '--nthreads', '1', 'scheduler:8786']
    volumes:
      - .:/workdir
      - data:/data
    environment:
      - PYTHONPATH=/workdir
  minio:
    image: minio/minio
    command: ['minio', 'server', '/data']
    environment:
    - MINIO_ACCESS_KEY
    - MINIO_SECRET_KEY
volumes:
  data:
    driver: local
